### PR TITLE
Branch code review fix v2.1

### LINKED ISSUE #221: Code Review: Nikhil
@nikkiDEEE 
1. Avoid complicated expressions – line 63 
Can consider breaking down into intermediate variables to improve readability	
image

2. Avoid magic strings – line 49, 50, 71, 73, 74 
Can consider reusing string constants for box parantheses, since they are recurring 

3. Write comments to the reader 
Can rephrase to sth like – “Sorts in descending order of importance”
image

### PR DESCRIPTION
**Pull request by nikkiDEEE**
fix #221

### CODE REVIEW

File: src/main/java/seedu/clialgo/Ui.java [hunk 1]
```diff
@@ -10,6 +13,13 @@ public class Ui {
 
     private static final String DIVIDER = "======================================================";
     private static final String EXIT_COMMAND = "exit";
+    private static final String LEFT_SQUARE_BRACKET = "[";
+    private static final String RIGHT_SQUARE_BRACKET = "]";
+    private static final String WHITE_SPACE = " ";
+    private static final String DOT_SPACE = ". ";
+    private static final String NOTE_LABEL = "[NOTE] ";
+    private static final String CODE_LABEL = "[CODE] ";
```
Comment (heejet) [inline src/main/java/seedu/clialgo/Ui.java:21]: I think the concept of replacing magic strings with constants is to improve code readability. If things like `.` and ` ` are replaced by constants i think it is over excessive. For `[` and `]`, I think putting it inside a method is sufficient.
image

I think `[NOTE]` and `[CODE]` should be replaced with constants but the rest I think is not necessary.
What do you guys think @nicholas132000 @ong-ck @lohjooh

**Review by heejet — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/clialgo/Ui.java (hunk 1 above)
Comment (nicholas132000) [reply src/main/java/seedu/clialgo/Ui.java:21]: image
According to sources online, string constants are used so that we do not need to type out the same thing multiple times. In this case, since the string constants for e.g. `LEFT_SQUARE_BRACKET` is more of a hassle to type that `[`, i think that your suggestion is valid.

Comment (nikkiDEEE) [reply src/main/java/seedu/clialgo/Ui.java:21]: i agree with the over-excessiveness, but it looked rather inconsistent in the method when `LEFT_SQUARE_BRACKET` was used alongside a `". "`, so i decided to use string constants all the way. thoughts?

@nicholas132000 our TA recommended using string constants in the code review for my part #221 

image

Comment (heejet) [reply src/main/java/seedu/clialgo/Ui.java:21]: In mine he said can either use constants or just use a method

Comment (nikkiDEEE) [reply src/main/java/seedu/clialgo/Ui.java:21]: Okay see what the rest think ig

Comment (ong-ck) [reply src/main/java/seedu/clialgo/Ui.java:21]: I am of similar opinion with @heejet in the using of a method to replace the magic strings instead of creating constants for the symbols used. The creating of constants for `NOTE_LABEL` and `CODE_LABEL` is definitely preferred but the others might really be a little excessive.

Comment (nikkiDEEE) [reply src/main/java/seedu/clialgo/Ui.java:21]: ok! will make the changes then

**Comment by nikkiDEEE** [comment]
removed excessive string constants

**Review by heejet — APPROVED** [review]
LGTM
